---
name: self-hosted BPI-R4 + main_router packages + GCC15 + 8GB RAM support

on:
  workflow_dispatch:

env:
  #
  #REMOTE_REPOSITORY: ww1150/openwrt
  #REMOTE_BRANCH: main-mt76-fw
  #
  REMOTE_REPOSITORY: openwrt/openwrt
  REMOTE_BRANCH: main
  RELEASE_PREFIX: Mediatek_mt7988a_bpi-r4

jobs:
  check_commits:
    name: Check Commits
    runs-on: ubuntu-24.04
    outputs:
      latest_commit_sha: ${{ steps.get_sha.outputs.latest_commit_sha }}
    steps:
      - name: Checkout remote repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REMOTE_REPOSITORY }}
          ref: ${{ env.REMOTE_BRANCH }}

      - name: Get the latest commit SHA
        id: get_sha
        run: |
          echo "latest_commit_sha=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "latest_commit_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  build:
    name: Build OpenWRT for BPI-R4 with BE14 and main-router packages
    needs: [ check_commits ]
    runs-on: self-hosted
    steps:
      #      - name: Install dependencies
      #        run: |
      #          sudo apt update
      #          sudo apt install -y \
      #            build-essential clang flex bison g++ gawk \
      #            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
      #            python3-setuptools rsync swig unzip zlib1g-dev file wget curl zstd \
      #            git
      #          sudo apt full-upgrade -y

      - name: Checkout remote repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REMOTE_REPOSITORY }}
          ref: ${{ env.REMOTE_BRANCH }}

      - name: Add custom feeds
        run: |
          echo 'src-git zapret https://github.com/remittor/zapret-openwrt.git' >> feeds.conf.default

      - name: Clone single packages
        run: |
          git clone https://github.com/jerrykuku/luci-theme-argon.git package/luci-theme-argon

      - name: Update and install feeds (with fallback to GitHub mirrors)
        run: |
          if ./scripts/feeds update -a; then
            echo "Successfully updated feeds from official sources."
          else
            echo "Official feeds update failed. Switching to GitHub mirrors and retrying."
            sed -i 's|git.openwrt.org/feed/\(.*\.git\)|github.com/openwrt/\1|' feeds.conf.default
            sed -i 's|git.openwrt.org/project/\(.*\.git\)|github.com/openwrt/\1|' feeds.conf.default
            echo "Updated feeds.conf.default:"
            cat feeds.conf.default
            ./scripts/feeds update -a
          fi

          echo "Feeds updated successfully. Now installing all packages."
          ./scripts/feeds install -a

      - name: Configure firmware image
        run: |
          curl -SL https://raw.githubusercontent.com/ww1150/openwrt-builder/refs/heads/nhp/configs/mediatek/mt7988a/bpi-r4 > .config
          curl -SL https://raw.githubusercontent.com/ww1150/openwrt-builder/refs/heads/nhp/configs/common/main-router >> .config
          curl -SL https://raw.githubusercontent.com/ww1150/openwrt-builder/refs/heads/nhp/configs/common/snapshot >> .config
          curl -SL https://raw.githubusercontent.com/ww1150/openwrt-builder/refs/heads/nhp/configs/common/optimize >> .config

      - name: Enable MLO
        run: |
          curl -SL https://raw.githubusercontent.com/ww1150/openwrt-builder/refs/heads/nhp/configs/common/mlo >> .config

      - name: Enable openssl
        run: |
          sed -i '/CONFIG_PACKAGE_wpad-mbedtls=y/d' .config
          curl -SL https://raw.githubusercontent.com/ww1150/openwrt-builder/refs/heads/nhp/configs/common/openssl >> .config

      - name: Add patches for 4GB WED
        run: |
          mkdir -p package/kernel/mt76/patches
          curl -SL https://github.com/LorenzoBianconi/mt76/commit/35bc8effe9e495ccded5d6722b299dafadce060e.patch > package/kernel/mt76/patches/999-mtk-mt76-mt7996-use-GFP_DMA32-for-page_pool.patch
          curl -SL https://github.com/LorenzoBianconi/net-next/commit/93dfca902f0d79126612b8e3cc553b5d891c1f55.patch > target/linux/mediatek/patches-6.12/999-wed-dma-mask-limitation.patch

      # From https://github.com/LorenzoBianconi/wireless-next/commit/3e444c68513934d47b019b236ad083c386b0d85b
      - name: Copy patches for WED kernel traceback
        run: |
          curl -SL https://raw.githubusercontent.com/ww1150/openwrt-builder/refs/heads/nhp/patches/999-use-proper-wed-reference-in-wed-kernel.patch > target/linux/mediatek/patches-6.12/999-use-proper-wed-reference-in-wed-kernel.patch
          curl -SL https://github.com/LorenzoBianconi/mt76/commit/92f22edf7fd119cde26218a7431919e4cdf1628e.patch > package/kernel/mt76/patches/999-use-proper-wed-reference-in-wed-mt76.patch


      #- name: Enable wolfssl
      #  run: |
      #    sed -i '/CONFIG_PACKAGE_wpad-mbedtls=y/d' .config
      #    curl -SL https://raw.githubusercontent.com/ww1150/openwrt-builder/refs/heads/nhp/configs/common/wolfssl >> .config

      #
      ### EEPROM FIX ###
      #
      ## https://github.com/openwrt/mt76/pull/954
      - name: Use patch from Yukariin
        run: |
          mkdir -p package/kernel/mt76/patches
          curl -SL https://github.com/openwrt/mt76/commit/8088940ffd047a6d282a95af829562e8038f5b2d.patch > package/kernel/mt76/patches/001-Add-tx_power-check-Yukariin.patch
      #
      ## https://github.com/openwrt/mt76/pull/968
      - name: Use patch from im-0
        run: |
          mkdir -p package/kernel/mt76/patches
          curl -SL https://github.com/openwrt/mt76/commit/aaf90b24fde77a38ee9f0a60d7097ded6a94ad1f.patch > package/kernel/mt76/patches/001-use-tx_power-from-default-fw-if-EEPROM-contains-0s-im-0.patch

      - name: Add librespeed-go
        run: |
          echo "CONFIG_PACKAGE_librespeed-go=y" >> .config

      - name: Prepare custom U-Boot source and fix build configuration
        run: |
          # --- Шаг 1: Создаем директорию для загрузок, если ее нет ---
          echo "Ensuring the 'dl' directory exists..."
          mkdir -p dl
          
          # --- Шаг 2: Клонируем нужный репозиторий и ветку ---
          echo "Cloning frank-w/u-boot repository, branch 2025-10-bpi..."
          git clone --depth=1 --branch 2025-10-bpi https://github.com/frank-w/u-boot.git custom-u-boot-source
          
          # --- Шаг 3: Создаем архив с тем именем, которое ожидает система ---
          echo "Creating source archive with custom content..."
          (cd custom-u-boot-source && tar -cjf ../dl/u-boot-2025.10.tar.bz2 .)
          
          # --- Шаг 4: Вычисляем хеш-сумму нашего нового архива ---
          echo "Calculating SHA256 hash of the new archive..."
          CUSTOM_HASH=$(sha256sum dl/u-boot-2025.10.tar.bz2 | awk '{print $1}')
          echo "New hash is: $CUSTOM_HASH"
          
          # --- Шаг 5: Обновляем ОРИГИНАЛЬНЫЙ Makefile ---
          echo "Updating the original U-Boot Makefile..."
          UBOOT_MAKEFILE="package/boot/uboot-mediatek/Makefile"
          
          # <<< НОВАЯ ПРОВЕРКА НАДЁЖНОСТИ >>>
          # Проверяем, существует ли файл, прежде чем пытаться его изменить.
          if [ ! -f "$UBOOT_MAKEFILE" ]; then
            echo "::error::Makefile not found at path: $UBOOT_MAKEFILE"
            exit 1
          fi
          
          # 5a: Вставляем наш кастомный хеш
          sed -i "s/PKG_HASH:=.*/PKG_HASH:=${CUSTOM_HASH}/" "$UBOOT_MAKEFILE"
          
          # 5b: <<< КЛЮЧЕВОЕ ИСПРАВЛЕНИЕ! >>>
          # Заставляем OpenWrt использовать правильное, короткое имя конфигурации
          sed -i "s/UBOOT_CONFIG:=mt7988a_bananapi_bpi-r4-emmc/UBOOT_CONFIG:=mt7988a_bpir4_emmc/" "$UBOOT_MAKEFILE"
          
          # --- Шаг 6: Проверяем, что получилось ---
          echo "--- Verifying final Makefile ---"
          grep "PKG_HASH" "$UBOOT_MAKEFILE"
          grep "UBOOT_CONFIG:=mt7988a_bpir4_emmc" "$UBOOT_MAKEFILE"
          echo "------------------------------"

      - name: Run defconfig
        run: |
          make defconfig

      - name: Test ONLY the U-Boot package compilation (Correct Method)
        run: |
          # --- Шаг 1: Собираем и устанавливаем только хост-инструменты ---
          # Эта команда соберет libdeflate-gzip и другие утилиты, не трогая пакеты прошивки.
          echo "--- Preparing host tools required for the build... ---"
          make tools/install -j$(nproc) V=s

          # --- Шаг 2: Компиляция только пакета U-Boot ---
          # Теперь, когда все инструменты гарантированно на месте, эта команда сработает.
          echo "--- Compiling U-Boot package... ---"
          make package/uboot-mediatek/compile V=s

      - name: Remove packages that are marked as modules
        run: |
          grep "=m" .config | grep -v 'CONFIG_PACKAGE_libustream-mbedtls=m' | while read -r line; do module=$(echo "$line" | cut -f1 -d'='); sed -i "s/^$line$/# $module is not set/" .config; done

      - name: Build the firmware image
        run: make -j $(nproc) defconfig download world

      - name: Package output
        run: tar -cvf bpi_r4-images.tar bin/targets/mediatek/filogic

      - name: Add config file
        run: cp .config  bin/targets/mediatek/filogic/config-full

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bpi_r4-images
          path: bpi_r4-images.tar

  release:
    name: Create release
    needs: [ build, check_commits ]
    if: needs.build.result == 'success'
    runs-on: ubuntu-24.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: bpi_r4-images

      - name: Extract artifacts
        run: tar xf bpi_r4-images.tar

      - name: Get current date
        run: echo "RELEASE_DATE=$(date +%F)" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@master
        with:
          files: bin/targets/mediatek/filogic/*
          tag_name: ${{ env.RELEASE_PREFIX }}-${{ env.REMOTE_BRANCH }}-${{ env.RELEASE_DATE }}
          name: OpenWRT BPI-R4 + MLO + main_router packages + GCC15 + WED 4GB patch + 8GB RAM support - ${{ env.REMOTE_BRANCH }} - ${{ env.RELEASE_DATE }}
          body: |
            Updated prebuilt images with main_router packages, patches for working 4GB RAM WED + 8GB RAM support build with GCC14 - ${{ env.RELEASE_DATE }},
            Build Commit: ${{ needs.check_commits.outputs.latest_commit_sha }}

      - name: Clean up old releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 5
          delete_tags: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}